.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-dotnet-developers-understanding-android-platform/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-accessibility/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-broadcast-receivers/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-constraint-layout/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-content-providers/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-effective-navigation/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-intents/table-of-contents"
.\downloader.ps1 -Course "https://app.pluralsight.com/library/courses/android-fundamentals-localization-internationalization/table-of-contents"